name: Ruby Gem

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      # uses: ruby/setup-ruby@v1 # v1.146.0
      # with:
      #   ruby-version: jruby
    - name: Publish to GPR
      run: |
        sudo apt remove ruby -y
        curl -s -L https://artifacts.elastic.co/downloads/logstash/logstash-8.17.0-linux-x86_64.tar.gz | tar -xz -C $HOME
        export LOGSTASH_HOME=$HOME/logstash-8.17.0
        export JRUBY_HOME=$LOGSTASH_HOME/vendor/jruby
        export GEM_HOME=$JRUBY_HOME
        export PATH=$PATH:$LOGSTASH_HOME/bin:$JRUBY_HOME/bin
        which logstash
        which gem 
        which bundle
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:github: Bearer ${{secrets.GITHUB_TOKEN}}\n" > $HOME/.gem/credentials
        bundle install
        gem build *.gemspec
        gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n:status: :ok\n" > $HOME/.gem/credentials
        bundle exec rake publish_gem
      env:
        GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
        OWNER: ${{ github.REPOSITORY_OWNER }}
